name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate Snake Game
        uses: platane/snk/svg-only@v3
        with:
          github_user_name: sikatikenmogne
          outputs: |
            assets/github-snake.svg
            assets/github-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # CHANGEMENT ICI : Git standard au lieu de l'action problématique
      - name: Commit and push snake files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add assets/
          git diff --staged --quiet || git commit -m "🐍 Update snake game"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}